name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Updated to v3

      - name: Setup Node
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --legacy-peer-deps # Added --legacy-peer-deps to avoid dependency conflicts

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3 # Already using the correct version
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo # Added this step to ensure the repo is checked out in the deploy job
        uses: actions/checkout@v3 # Updated to v3

      - name: Download artifact
        uses: actions/download-artifact@v3 # Updated to v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
